# Uncomment this line to define a global platform for your project
 platform :ios, '8.1'

use_frameworks!
target 'DYZB' do
pod 'Alamofire','3.2.1'
pod 'SDWebImage'
pod 'SnapKit', '~> 0.19.1'
pod 'SVProgressHUD'
end
