# Uncomment this line to define a global platform for your project
 platform :ios, '8.1'

use_frameworks!
target 'DYZB' do
pod 'Alamofire'
pod 'SDWebImage', '~> 3.8.0'
pod 'SnapKit'
pod 'SVProgressHUD'
pod 'MJRefresh', '~> 3.1.12'
pod 'LFLiveKit', '~> 2.6'
pod 'MJExtension', '~> 3.0.13'
pod 'BarrageRenderer', '~> 1.9.0'    # 弹幕
pod 'XHLaunchAd', '~> 3.3.0'         # 广告
pod 'UICollectionViewLeftAlignedLayout'
#pod 'STCustomWidthLayout'
pod 'STRowLayout'
pod 'IQKeyboardManagerSwift'         # 键盘遮挡输入框
pod 'SCLAlertView'                   # 警告框控件
#pod 'RealmSwift'

#pod 'FDFullscreenPopGesture'    # 一个丝滑的全屏滑动返回手势(百度大神之作) oc版本
pod 'TZImagePickerController'   # 相册选择 oc版本
#pod 'HYBUnicodeReadable'       # 会和XHLaunchAd框架产生冲突,暂时关闭
end
