# Uncomment this line to define a global platform for your project
 platform :ios, '8.1'

use_frameworks!
target 'DYZB' do
pod 'Alamofire'
pod 'SDWebImage'
pod 'SnapKit'
pod 'SVProgressHUD'
pod 'MJRefresh', '~> 3.1.12'
pod 'LFLiveKit', '~> 2.3'
pod 'MJExtension', '~> 3.0.13'
pod 'BarrageRenderer', '~> 1.9.0'
end
